FROM node:lts-alpine as build

RUN mkdir -p /usr/src/app/frontend

WORKDIR /usr/src/app/frontend

COPY package*.json ./
RUN npm ci

COPY . .

# Set env vars
ARG REACT_APP_PORT
ARG REACT_APP_PROXY
ARG REACT_APP_HOST_IP
ARG REACT_APP_HOST_NAME
ARG REACT_APP_PROD

ENV REACT_APP_PORT=$REACT_APP_PORT
ENV REACT_APP_PROXY=$REACT_APP_PROXY
ENV REACT_APP_HOST_IP=$REACT_APP_HOST_IP
ENV REACT_APP_HOST_NAME=$REACT_APP_HOST_NAME
ENV REACT_APP_PROD=$REACT_APP_PROD

CMD ["npm", "start"]
