version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: 
      context: ./frontend # path to dockerfile
      # for some reason I can't use environment for react env frontend variables that I want to access in react
      args: 
        REACT_APP_PORT: ${REACT_APP_PORT}
        REACT_APP_PROXY: ${NGINX_PORT}
        REACT_APP_HOST_IP: ${HOST_IP}
        REACT_APP_HOST_NAME: ${HOST_NAME}
        REACT_APP_PROD: ${PROD}
    expose: 
      - ${REACT_APP_PORT}
    environment: # accessible in dockerfile
      NGINX_APP_PORT: ${REACT_APP_PORT}
    image: ${CONTAINER_FRONTEND_NAME}
    container_name: ${CONTAINER_FRONTEND_NAME}
    restart: always

  nginx_reverse_proxy:
    build: ./nginx
    environment: 
      NGINX_FRONTEND_PORT: ${REACT_APP_PORT}
      NGINX_FRONTEND_NAME: ${CONTAINER_FRONTEND_NAME}
      NGINX_BACKEND_PORT: ${FLASK_APP_PORT}
      NGINX_BACKEND_NAME: ${CONTAINER_BACKEND_NAME}
      NGINX_PORT: ${NGINX_PORT}
    ports: # Port binding from docker container to host
      - "${NGINX_PORT}:${NGINX_PORT}"
    image: ${CONTAINER_NGINX_NAME}
    container_name: ${CONTAINER_NGINX_NAME}
    restart: always

  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    # I should just be able to do this but for some reason nginx doesn't like just this
    expose: 
      - ${FLASK_APP_PORT}
    environment: 
      # don't need the FLASK_APP_ but here to keep the convention needed for the frontend(react)
      FLASK_APP_PORT: ${FLASK_APP_PORT}
      FLASK_APP_FRONTEND: ${REACT_APP_HOST}
      FLASK_APP_PROXY: ${NGINX_PORT}
      FLASK_APP_PROD: ${PROD}
      FLASK_APP_HOST_IP: ${HOST_IP}
      FLASK_APP_HOST_NAME: ${HOST_NAME}
    image: ${CONTAINER_BACKEND_NAME}
    container_name: ${CONTAINER_BACKEND_NAME}
    restart: always